### ISSUE TITLE
日志中添加日期时间

### ISSUE THREAD

**Issue by YJBeetle** [zhiyb/MinecraftScripts#2]
日志中诸如：

`Fetching manifest...`
`Latest snapshot: 1.12.1 (2017-08-03T12:40:39+00:00)`
`File server/1.12.1.jar already exists`
`Fetching manifest...`
`Latest snapshot: 1.12.1 (2017-08-03T12:40:39+00:00)`
`File server/1.12.1.jar already exists`
`Fetching manifest...`
`Latest snapshot: 1.12.1 (2017-08-03T12:40:39+00:00)`
`File server/1.12.1.jar already exists`
`Fetching manifest...`
`Latest snapshot: 1.12.1 (2017-08-03T12:40:39+00:00)`
`File server/1.12.1.jar already exists`
`./server_update.sh: 第 30 行:echo: 写错误: 设备上没有空间`
`Fetching manifest...`
`Latest snapshot: 1.12.1 (2017-08-03T12:40:39+00:00)`
`File server/1.12.1.jar already exists`
`./server_update.sh: 第 30 行:echo: 写错误: 设备上没有空间`

出现错误的时间没有记录，希望可以在其中输出日期时间

**Comment by zhiyb** [comment]
Please try out comment 56a18a1

**Comment by YJBeetle** [comment]
Thanks , its very nice
